<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35899" started-at="2020-01-09T18:50:37 IST" finished-at="2020-01-09T18:51:13 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35899" started-at="2020-01-09T18:50:37 IST" finished-at="2020-01-09T18:51:13 IST">
      <class name="qa.NewLeadTest">
        <test-method status="PASS" signature="tierUp()[pri:0, instance:qa.NewLeadTest@3b088d51]" name="tierUp" is-config="true" duration-ms="11089" started-at="2020-01-09T18:50:37 IST" finished-at="2020-01-09T18:50:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tierUp -->
        <test-method status="PASS" signature="login()[pri:1, instance:qa.NewLeadTest@3b088d51]" name="login" duration-ms="6359" started-at="2020-01-09T18:50:48 IST" finished-at="2020-01-09T18:50:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="app_launch()[pri:2, instance:qa.NewLeadTest@3b088d51]" name="app_launch" duration-ms="10429" started-at="2020-01-09T18:50:55 IST" finished-at="2020-01-09T18:51:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- app_launch -->
        <test-method status="PASS" signature="create_new_lead()[pri:3, instance:qa.NewLeadTest@3b088d51]" name="create_new_lead" duration-ms="1420" started-at="2020-01-09T18:51:05 IST" finished-at="2020-01-09T18:51:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_new_lead -->
        <test-method status="FAIL" signature="fill_form1()[pri:4, instance:qa.NewLeadTest@3b088d51]" name="fill_form1" duration-ms="6550" started-at="2020-01-09T18:51:07 IST" finished-at="2020-01-09T18:51:13 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at sft.ForceObject.Select.Select.select(Select.java:61)
at sft.ForceObject.Select.Select.set(Select.java:66)
at qa.NewLeadTest.fill_form1(NewLeadTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fill_form1 -->
        <test-method status="PASS" signature="tierDown()[pri:0, instance:qa.NewLeadTest@3b088d51]" name="tierDown" is-config="true" duration-ms="0" started-at="2020-01-09T18:51:13 IST" finished-at="2020-01-09T18:51:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tierDown -->
      </class> <!-- qa.NewLeadTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
